apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: wbkf944zi-nodejs 
  janus-idp.io/tekton: wbkf944zi-nodejs
  backstage.io/kubernetes-id: wbkf944zi-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: wbkf944zi-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  